### PR TITLE
Stockfish `Assertion failed: count<Pt>(c) == 1` with changed knight value

### PR DESCRIPTION
**Pull request by FishChess**
Hi Dear Tord

We found a bug in all stockfish version from stockfish 1 to stockfish 15

Seems to happen somewhat often with changed knight value between pieces, but I couldn't reproduce with all different values.

 _**debug mode**_

```
Stockfish 15.1 by the Stockfish developers (see AUTHORS file)
setoption name Use NNUE value false
position fen rnbqk1nr/ppp2ppp/4p3/3pP3/3P4/2P5/P1P2PPP/R1BQKBNR b KQkq - 0 5
go depth 26
info string classical evaluation enabled
info depth 1 seldepth 1 multipv 1 score cp -36 nodes 28 nps 14000 hashfull 0 tbhits 0 time 2 pv b8c6
info depth 2 seldepth 2 multipv 1 score cp -36 nodes 107 nps 53500 hashfull 0 tbhits 0 time 2 pv b8c6
....
info depth 25 currmove g8e7 currmovenumber 1
Assertion failed: count<Pt>(c) == 1, file position.h, line 255
```

I reported these issues to official Stockfish, but they said this is not important issues because occurred in classical stockfish rule:

> _I think this just affects the classical code, and that one is considered frozen. I see no real point in making this change. Adding a comment near the type values could be done._
> _Originally posted by @vondele in https://github.com/official-stockfish/Stockfish/issues/4262#issuecomment-1343220558_

To avoid this error, I disabled assert 

_in bitboard.h_

```
inline Square lsb(Bitboard b) {
//  assert(b);
  unsigned long idx;
  _BitScanForward64(&idx, b);
  return (Square) idx;
}
```
how to solve this problem ?

Thanks and Regards

### CODE REVIEW

**Comment by vondele** [comment]
as mentioned elsewhere this is a non-issue, a no bug is present in SF. Essentially the piece values you introduce in the code are not supported. Stop filing issues.

**Comment by FishChess** [comment]
After TRUE commenting this issue [428](https://github.com/official-stockfish/Stockfish/pull/4283)  , the repository's owner (@vondele ) restricted me rights on official Stockfish for no reason.

 Also my best friend (@atumanian) who ever gave his best blocked by @vondele just for TRUE commenting


> I've blocked @atumanian in light of this discussion.
> 
> _Originally posted by @vondele in https://github.com/official-stockfish/Stockfish/issues/4195#issuecomment-1279968617_
>       

@romstad , I think there is no freedom in commenting, please consider it

Thanks

**Comment by atumanian** [comment]
Hi, @FishChess !
Thank you for calling me your best friend and appreciating my contributions! Indeed, Vondele has gone too far and blocks good contributors just for disagreeing with him. I've currently been considering creating a topic in the Fishcooking forum called "The Stockfish/Fishtest organization has become too corrupted".

**Comment by FishChess** [comment]
> I've currently been considering creating a topic in the Fishcooking forum called "The Stockfish/Fishtest organization has become too corrupted".

Thanks @atumanian , I'm very eager to see your topic in the Fishcooking . I hope all developers will pay attention to it

@ppigazzini @snicolet @dav1312 @ianfab @vdbergh @mstembera @sopel97 @peregrineshahin @Craftyawesome @MinetaS @lonfom169 @FauziAkram @VoyagerOne @FritzChess @Vizvezdenec @Clausable @pb00068 @dsmsgms @kurt22i @shtayerc @joergoster @RogerThiede @niklasf @linrock @noobpwnftw @XInTheDark @candirufish @nodchip @jxu @nathan-lc0 @shorome2

**Comment by Vizvezdenec** [comment]
Well, let's take it apart in parts, what you wrote)) It seems that you are really shell-shocked, offended by life imbecile)) Can I tell you in your eyes, are you ready to come to listen?) All that garbage you wrote is a simple lie, you homeroom Rambo)) just because you wrote a lot, your life won’t get better)) to talk a lot is not to carry heavy bags, a lot of people like you thawed out in the spring)) They say about people like you: Mom didn’t want, dad didn’t try) Try to analyze my message to you and draw conclusions for yourself)

**Pull request closed without merging**
